server:
  port: 8081

spring:
  application:
    name: MO-SERVICE

datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

jpa:
    properties:
      hibernate:
          connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://TEPF32GHQW.iuser.iroot.adidom.com:9190/eureka/
    instance:
      hostname: TEPF32GHQW.iuser.iroot.adidom.com

zipkin:
  enabled: true
  base-url: http://TEPF32GHQW.iuser.iroot.adidom.com:9090/
