server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MO-SERVICE
          uri: lb://MO-SERVICE
          predicates:
            - Path=/mo/**
        - id: DDD-SERVICE
          uri: lb://DDD-SERVICE
          predicates:
            - Path=/ddd/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://TEPF32GHQW.iuser.iroot.adidom.com:9190/eureka/
    instance:
      hostname: TEPF32GHQW.iuser.iroot.adidom.com