server:
  port: 8082

spring:
  application:
    name: DDD-SERVICE

datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

jpa:
    properties:
      hibernate:
          connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: none

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://TEPF32GHQW.iuser.iroot.adidom.com:9190/eureka/
    instance:
      hostname: TEPF32GHQW.iuser.iroot.adidom.com

resilience4j:
  circuitbreaker:
    configs:
      shared:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      moservicecall:
        base-config: shared

zipkin:
  enabled: true
  base-url: http://TEPF32GHQW.iuser.iroot.adidom.com:9090/